# © 2019 - today Numigi (tm) and all its contributors (https://bit.ly/numigiens)
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    'name': 'Main Module',
    'version': '1.0.0',
    'author': 'Numigi',
    'maintainer': 'Numigi',
    'website': 'https://www.numigi.com',
    'license': 'LGPL-3',
    'category': 'Other',
    'summary': 'Install all addons required for testing.',
    'depends': [
        'payroll_code_on_task_type',
        'payroll_period',
        'payroll_preparation',
        'payroll_preparation_export_wizard',
        'payroll_preparation_from_project',
        'payroll_preparation_from_timesheet',
        'payroll_preparation_prorata',
        'payroll_preparation_to_payslip',
        'payroll_preparation_to_payslip_analytic',
        'payroll_preparation_to_payslip_project',
        'project_timesheet_time_control_enhanced',
        'project_timesheet_time_control_sheet',
        'timesheet_edit_only_today',
        'timesheet_edit_only_today_grid',
        'timesheet_holidays_time_control_binding',
        'timesheet_list_description_after_task',
        'timesheet_list_employee',
        'timesheet_multi_line_wizard',
        'timesheet_multi_line_wizard_grid',
        'timesheet_multi_line_wizard_security',
        'timesheet_payroll_period',
        'timesheet_validation_status',
        'timesheet_validation_status_enterprise',
    ],
    'installable': True,
}
